// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef graftaleditor_hh
#define graftaleditor_hh
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Button.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *win;
  Fl_Input *graftal;
private:
  inline void cb_graftal_i(Fl_Input*, UserInterface*);
  static void cb_graftal(Fl_Input*, UserInterface*);
public:
  Fl_Text_Editor *rules;
  Fl_Button *next;
  Fl_Button *quit;
private:
  inline void cb_quit_i(Fl_Button*, void*);
  static void cb_quit(Fl_Button*, void*);
public:
  virtual void new_graftal(const char *txt);
  virtual ~UserInterface();
};
#endif
