// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "graftaleditor.hh"
#include <SDL2/SDL.h>

void UserInterface::cb_graftal_i(Fl_Input* o, UserInterface*) {
  this->new_graftal(o->value());
}
void UserInterface::cb_graftal(Fl_Input* o, UserInterface* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_graftal_i(o,v);
}

void UserInterface::cb_quit_i(Fl_Button*, void*) {
  win->hide();
}
void UserInterface::cb_quit(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_quit_i(o,v);
}

UserInterface::UserInterface() {
  { win = new Fl_Double_Window(570, 410, "Graftals");
    win->user_data((void*)(this));
    { graftal = new Fl_Input(95, 5, 475, 30, "&Graftal");
      graftal->tooltip("Enter the Graftal here.");
      graftal->callback((Fl_Callback*)cb_graftal, (void*)(this));
    } // Fl_Input* graftal
    { rules = new Fl_Text_Editor(95, 70, 475, 340, "&Rules");
      rules->tooltip("Enter the graphtal transformation mapping rules here.");
      rules->buffer(new Fl_Text_Buffer);
    } // Fl_Text_Editor* rules
    { next = new Fl_Button(5, 70, 85, 25, "&Next");
      next->tooltip("Next Iteration.");
    } // Fl_Button* next
    { quit = new Fl_Button(20, 380, 60, 25, "&Quit");
      quit->tooltip("Quit this ugly program.");
      quit->callback((Fl_Callback*)cb_quit);
    } // Fl_Button* quit
    { Fl_Button* o = new Fl_Button(5, 100, 85, 25, "&Previous");
      o->tooltip("Previous Iteration.");
    } // Fl_Button* o
    win->show();
    win->end();
  } // Fl_Double_Window* win
}

/**
   Set the new Graftal.
*/
void UserInterface::new_graftal(const char *txt) {
  //
}

UserInterface::~UserInterface() {
  //
}
